# This file is designed to run and test the production build on a development machine. The acutal docker-compose.yml file is customized on the server.
name: mjml-server
services:
  web:
    build:
      context: .
    image: repo.enga.systems/mjml-server:latest
    container_name: mjml-server
    volumes:
      - ./https:/app/https
      - ./keys:/app/keys
    restart: no
    env_file:
      - ".env"
      - ".env.production"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # Max size per file
        max-file: "3"     # Keep only 3 old files
    networks:
      - backend

networks:
  backend:
    name: backend_network
    external: true
