services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: mjml-server-dev
    # command: sh -c "npx nodemon ./src/server.js"
    ports:
      - "3003:3003"
    env_file:
      - .env
    volumes:
      - .:/app # Mount your code
      - /app/node_modules
    networks:
      - backend  # Join the existing network

networks:
  backend:
    external: true
    name: backend_network